version: '2'

services:
  db:
    image: mongo
    ports:
      - 27017
  web:
    build: .
    command: npm start
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
